<a href="https://colab.research.google.com/github/kekele-star/pytorch_course/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals
 Resource notebook: https://www.learnpytorch.io/


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)  # check the version of pytorch you're using

2.0.1+cu118


## Introduction to Tensors
### Creating tensors

PyTorch tensors are created using `torch.Tensor()`  = https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar
scalar = torch.tensor(7)  # torch.tensor is a multi-dimensional matrix containing element of a single data type
scalar


tensor(7)

####  A scalar has no dimensions.
It's just a single number.
It's number of direction is zero i.e 0.

ndim = number of dimensions.

##  

#### Naming in scalar approach:
Lower(a)



In [ ]:
scalar.ndim  #dimensions a scalar. Dimension is the number of closing square brackets.

0

In [ ]:
# Get tensor back as python int
scalar.item() # get number in torch.tensor(7) out of tensor type

7

### A vector has mass and direction.
A vector is a number with direction but can also have many other numbers.
Eg: wind speed with direction
A vector usual has more than one number unlike a scalar


### Naming in scalar approach:
Lower(y)

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

### Shape is the elements in the within the defined dimension

---



In [ ]:
vector.shape

torch.Size([2])

### A MATRIX is a 2-dimensional array of numbers.
Number of dimensions is 2

### Naming in MATRIX approach:
Upper(Q)

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1] # finding the exact position an element in a MATRIX

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

## Tensor
A tensor is an n-dimensional array of numbers. It's dimension can be any number, a 0-dimension tensor is a scalar, a 1-dimensio tensor is a vector

### Naming in vector approach:
Upper(X)

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> updates random numbers

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3954, 0.0264, 0.9431, 0.0589],
        [0.5058, 0.2066, 0.9636, 0.5982],
        [0.1804, 0.2082, 0.7854, 0.5841]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, , colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones


In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(3, 4) # it can also be written as torch.zeros(size=(3,1)), it's the same thing
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones = torch.ones(5, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensor-like

In [ ]:
# use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Tensor datatypes
**Note:** Tensor datatypes is  one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

### Precision in computing
In computer science, the precision of a numerical quantity is a measure of the detail n whihc the quality is expressed. This is usually measured in bits, but sometimes in decimal digits. It is related to precision in mathematics, whihc describes the number of digits that are used to express a value.

link: https://en.wikipedia.org/wiki/Precision_(computer_science)#:~:text=In%20computer%20science%2C&20the%20precisioin,used%20to%20express%20a%20value.


In [ ]:
# creating tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# create a  range of tensors  in a range
torch.__version__

'2.0.1+cu118'

### Tensor datatypes




In [ ]:
# Plot 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (eg:flaot32, float16). if you make dtype=none, it's automatically set to float 32
                               device=None, # what device is your tensor on eg: cuda
                               requires_grad=False) # whether or not to track gradients with this tensor opertions
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor # checking to see if different datatypes will flag an error

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2955, 0.4915, 0.7933, 0.9040],
        [0.7526, 0.0959, 0.3977, 0.8088],
        [0.3935, 0.3965, 0.1182, 0.3835]])

In [ ]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [ ]:
# find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"shape of data: {some_tensor.shape}")  # nb: some_tensor.shape is an attribute
print(f"size of data: {some_tensor.size}") # nb: some_tensor.size is a function, not an attribute

tensor([[0.2955, 0.4915, 0.7933, 0.9040],
        [0.7526, 0.0959, 0.3977, 0.8088],
        [0.3935, 0.3965, 0.1182, 0.3835]])
Datatype of tensor: torch.float32
shape of data: torch.Size([3, 4])
size of data: <built-in method size of Tensor object at 0x7c2dcf82fe70>


### Manipulating Tensors(tensor operations)
Tensor operations include:
  * Addition
  * Subtraction
  * Multiplication (element-wise)
  * Division
  * Matrix multiplication

In [ ]:
# create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tennsor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# subtract
tensor - 10

tensor([-9, -8, -7])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html


There are two main rules that performing matrix multiplication needs to satisfy otherwise, you'd run into an error:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` wont work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
*
eg: running the code: `torch.matmul(torch.rand(10,10), torch.rand(7,10)` will flag an error

* but running the code `torch.matmul(torch.rand(10,7), torch.rand(7,10)` will not flag any error.

2. The resulting matrix has the shape of the **outer dimensions**:
* `(3,2) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# element wise multiplication
print(tensor, "*", tensor)
print(f"EqualsL {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
EqualsL tensor([1, 4, 9])


### vectorization
Vectorization is a technique by which you can make your code execute fast. It is a very interesting and important way to optimize algorithms when you are implementing it from scratch.

######Eg: `torch.matmul(tensor, tensor)`
The code above will run faster as compare to using a function.

######example below:

`value = 0
for i in range(len(tensor));
   vaule += tensor[i] * tensor[i]
 print(value)`

In [ ]:
# matrix multiplication
torch.matmul(tensor, tensor)  # torch.matmul is faster compared to using a loop to run a math function eg:
# value = 0
# for i in range(len(tensor)):
#   vaule += tensor[i] * tensor[i]
# print(value)

tensor(14)

### One of the most common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

# torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul(it's an alias for torch.matmul)
torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_B.T # dot T stands for transpose

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)

print(f"\nOutput shape: {output.shape}")
torch.matmul(tensor_A, tensor_B.T)

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = tensor([[ 7,  8,  9],
        [10, 11, 12]])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# find the min
torch.min(x), #or x.min()

(tensor(1),)

In [ ]:
# find the max
x.max()

tensor(91)

In [ ]:
# find the mean - note: the torch.mean() function requires a tensor of float32 to work
torch.mean(x.type(torch.float32)) # or x.type(torch.float32).mean()

tensor(46.)

In [ ]:
# find the sum
x.sum()

### Finding the positional min and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target where the minimum value occurs
x[0]

tensor(1)

In [ ]:
# create a tensor
import

In [ ]:
!nvidia-smi

Thu Jul 27 12:49:00 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------